# Generated by Django 3.2 on 2021-05-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requested_principal', models.DecimalField(decimal_places=0, max_digits=5)),
                ('interest_rate', models.FloatField(max_length=3)),
                ('status', models.CharField(default='N', max_length=1)),
                ('emi', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
