# Generated by Django 3.2.2 on 2021-05-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20210509_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['pk']},
        ),
    ]
