name: tests
on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: flake8 Linter
        run: pip install flake8 && flake8 --statistics --count

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: test and coverage
        run: coverage erase && coverage run ./manage.py test && coverage report
